Form Project Review
TashfeenRao/re-former pull request #4
Opened 2020-02-13 16:36 UTC by TashfeenRao

2020-02-13 23:54 UTC, maelfosso requested changes
# Changes required

Hello @TashfeenRao @konyan ,

Nice improvements :clap: 
However, there are still some errors

1. I got this error when creating a new user
![Screenshot from 2020-02-13 18-43-57](https://user-images.githubusercontent.com/8848104/74488714-1a7f5b80-4e91-11ea-8a1f-888b0f8ebe9e.png)

2. I got this error when trying to update an user
![Screenshot from 2020-02-13 18-47-41](https://user-images.githubusercontent.com/8848104/74488823-5f0af700-4e91-11ea-9469-b678d0a99107.png)

3. You should go through 3 forms, describe [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png), [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) and [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png). We need to see those 3 forms (the 2 first should be commented).
Please, add the 3 first in `edit.html.erb` and `new.html.erb`

4. Please, read the comments left below.

Kindly make the changes and submit a new code review request. Don't create a new one, please, just use the same link with a description added.

Thanks
Mael FOSSO

2020-02-13 23:54 UTC, maelfosso commented on app/controllers/users_controller.rb
> +      redirect_to @user
According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_create.png), you have to redirect to `new_user_path`

2020-02-13 23:54 UTC, maelfosso commented on app/controllers/users_controller.rb
> +      redirect_to @user
You have to redirect to `edit_user_path`

2020-02-14 17:44 UTC, samgaco commented
Hi @TashfeenRao and @konyan :high_brightness: 

Everything is working now and corrected as suggested before, the project is approved :+1: 

-----------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2020-03-19 22:02 UTC, merged